name: Feature Request
description: Suggest a new feature for Aerion
labels: ["feature request"]
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - Mac
        - Windows
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - x86_64
        - arm64
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux Distro
      description: Required if OS is Linux
      placeholder: e.g. Ubuntu, Fedora, Arch

  - type: input
    id: distro-version
    attributes:
      label: Linux Distro Version
      description: Required if OS is Linux
      placeholder: e.g. 24.04, 41, Rolling

  - type: dropdown
    id: webkit2gtk
    attributes:
      label: Is webkit2gtk 4.1 installed?
      description: Required if OS is Linux
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: install-method
    attributes:
      label: Install Method
      options:
        - Windows Binary
        - MacOS DMG
        - Linux Binary
        - Flatpak
        - Compile from Source
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Aerion Version
      description: "Find out what version you are running from Aerion at ⚙️ (settings) --> About."
      placeholder: e.g. v0.1.25
    validations:
      required: true
      pattern: "^(v|0)\\d*\\.\\d+\\.\\d+"
      validation_message: "Version must start with 'v' or '0' and follow the format (e.g. v0.1.25 or 0.1.25)"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see
    validations:
      required: true
