// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {certificate} from '../models';
import {account} from '../models';
import {carddav} from '../models';
import {message} from '../models';
import {folder} from '../models';
import {app} from '../models';
import {contact} from '../models';
import {context} from '../models';
import {smtp} from '../models';
import {imap} from '../models';
import {settings} from '../models';
import {pgp} from '../models';
import {smime} from '../models';
import {appstate} from '../models';
import {sync} from '../models';
import {draft} from '../models';

export function AcceptCertificate(arg1:string,arg2:certificate.CertificateInfo,arg3:boolean):Promise<void>;

export function AddAccount(arg1:account.AccountConfig):Promise<account.Account>;

export function AddContact(arg1:string,arg2:string):Promise<void>;

export function AddContactSource(arg1:carddav.SourceConfig):Promise<carddav.Source>;

export function AddImageAllowlist(arg1:string,arg2:string):Promise<void>;

export function AddPGPKeyServer(arg1:string):Promise<void>;

export function Archive(arg1:Array<string>):Promise<void>;

export function BroadcastAccountUpdated(arg1:string):Promise<void>;

export function BroadcastContactsUpdated(arg1:string):Promise<void>;

export function BroadcastThemeChange(arg1:string):Promise<void>;

export function CanUndo():Promise<boolean>;

export function CancelAccountSync(arg1:string):Promise<void>;

export function CancelAllSyncs():Promise<void>;

export function CancelContactSourceOAuthFlow():Promise<void>;

export function CancelFolderSync(arg1:string,arg2:string):Promise<void>;

export function CancelOAuthFlow():Promise<void>;

export function CheckRecipientCerts(arg1:Array<string>):Promise<Record<string, boolean>>;

export function CheckRecipientPGPKeys(arg1:Array<string>):Promise<Record<string, boolean>>;

export function ClearContactSourceError(arg1:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function CompleteContactSourceOAuthSetup(arg1:string,arg2:number):Promise<carddav.Source>;

export function CompleteOAuthAccountSetup(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<account.Account>;

export function CopyToFolder(arg1:Array<string>,arg2:string):Promise<void>;

export function CreateIdentity(arg1:string,arg2:account.IdentityConfig):Promise<account.Identity>;

export function DeleteContact(arg1:string):Promise<void>;

export function DeleteContactSource(arg1:string):Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function DeleteIdentity(arg1:string):Promise<void>;

export function DeleteLocalMessages(arg1:Array<string>):Promise<void>;

export function DeletePGPKey(arg1:string):Promise<void>;

export function DeletePGPSenderKey(arg1:string):Promise<void>;

export function DeletePermanently(arg1:Array<string>):Promise<void>;

export function DeleteSMIMECertificate(arg1:string):Promise<void>;

export function DeleteSenderCert(arg1:string):Promise<void>;

export function DiscoverCardDAVAddressbooks(arg1:string,arg2:string,arg3:string):Promise<Array<carddav.AddressbookInfo>>;

export function DownloadAttachment(arg1:string,arg2:string):Promise<string>;

export function DownloadEncryptedAttachment(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EmptyTrash(arg1:string,arg2:string):Promise<void>;

export function FetchMessageBody(arg1:string):Promise<message.Message>;

export function FetchServerMessage(arg1:string,arg2:string,arg3:number):Promise<message.Message>;

export function ForceSyncFolder(arg1:string,arg2:string):Promise<void>;

export function GetAccount(arg1:string):Promise<account.Account>;

export function GetAccountFoldersForMapping(arg1:string):Promise<Array<folder.Folder>>;

export function GetAccounts():Promise<Array<account.Account>>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetAttachment(arg1:string):Promise<message.Attachment>;

export function GetAttachments(arg1:string):Promise<Array<message.Attachment>>;

export function GetAutoDetectedFolders(arg1:string):Promise<Record<string, string>>;

export function GetAutostart():Promise<boolean>;

export function GetConfiguredOAuthProviders():Promise<Array<string>>;

export function GetConnectedComposers():Promise<number>;

export function GetContact(arg1:string):Promise<contact.Contact>;

export function GetContactSource(arg1:string):Promise<carddav.Source>;

export function GetContactSourceErrors():Promise<Array<carddav.SourceError>>;

export function GetContactSourceStats():Promise<Record<string, any>>;

export function GetContactSources():Promise<Array<carddav.Source>>;

export function GetContext():Promise<context.Context>;

export function GetConversation(arg1:string,arg2:string):Promise<message.Conversation>;

export function GetConversationCount(arg1:string,arg2:string):Promise<number>;

export function GetConversations(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<Array<message.Conversation>>;

export function GetDraft(arg1:string):Promise<smtp.ComposeMessage>;

export function GetFTSIndexStatus(arg1:string):Promise<message.FTSIndexStatus>;

export function GetFTSIndexStatusAll():Promise<Record<string, message.FTSIndexStatus>>;

export function GetFolderTree(arg1:string):Promise<Array<folder.FolderTree>>;

export function GetFolders(arg1:string):Promise<Array<folder.Folder>>;

export function GetIMAPConnectionForUndo(arg1:context.Context,arg2:string):Promise<imap.Client>;

export function GetIPCAddress():Promise<string>;

export function GetIdentities(arg1:string):Promise<Array<account.Identity>>;

export function GetIdentity(arg1:string):Promise<account.Identity>;

export function GetImageAllowlist():Promise<Array<settings.AllowlistEntry>>;

export function GetInlineAttachments(arg1:string):Promise<Record<string, string>>;

export function GetLanguage():Promise<string>;

export function GetLinkedAccountsForContactSync():Promise<Array<app.LinkedAccountInfo>>;

export function GetMarkAsReadDelay():Promise<number>;

export function GetMessage(arg1:string):Promise<message.Message>;

export function GetMessageCount(arg1:string,arg2:string):Promise<number>;

export function GetMessageListDensity():Promise<string>;

export function GetMessageListSortOrder():Promise<string>;

export function GetMessageSource(arg1:string):Promise<string>;

export function GetMessages(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<message.MessageHeader>>;

export function GetOAuthStatus(arg1:string):Promise<app.OAuthStatus>;

export function GetPGPEncryptPolicy(arg1:string):Promise<string>;

export function GetPGPKeyForEmail(arg1:string,arg2:string):Promise<pgp.Key>;

export function GetPGPKeyServers():Promise<Array<pgp.KeyServer>>;

export function GetPGPSignPolicy(arg1:string):Promise<string>;

export function GetPendingMailto():Promise<app.MailtoData>;

export function GetReadReceiptResponsePolicy():Promise<string>;

export function GetRunBackground():Promise<boolean>;

export function GetSMIMECertificateForEmail(arg1:string,arg2:string):Promise<smime.Certificate>;

export function GetSMIMEEncryptPolicy(arg1:string):Promise<string>;

export function GetSMIMESignPolicy(arg1:string):Promise<string>;

export function GetSearchCount(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetSearchCountUnifiedInbox(arg1:string):Promise<number>;

export function GetShowTitleBar():Promise<boolean>;

export function GetSourceAddressbooks(arg1:string):Promise<Array<carddav.Addressbook>>;

export function GetSpecialFolder(arg1:string,arg2:folder.Type):Promise<folder.Folder>;

export function GetStartHidden():Promise<boolean>;

export function GetStartHiddenActive():Promise<boolean>;

export function GetSystemTheme():Promise<string>;

export function GetTermsAccepted():Promise<boolean>;

export function GetThemeMode():Promise<string>;

export function GetTrustedCertificates(arg1:Array<string>):Promise<Array<certificate.CertificateInfo>>;

export function GetUIState():Promise<appstate.UIState>;

export function GetUndoDescription():Promise<string>;

export function GetUnifiedInboxConversations(arg1:number,arg2:number,arg3:string):Promise<Array<message.Conversation>>;

export function GetUnifiedInboxCount():Promise<number>;

export function GetUnifiedInboxUnreadCount():Promise<number>;

export function HasPGPKey(arg1:string):Promise<boolean>;

export function HasSMIMECertificate(arg1:string):Promise<boolean>;

export function IMAPSearchFolder(arg1:string,arg2:string,arg3:string,arg4:number):Promise<sync.IMAPSearchResponse>;

export function IgnoreReadReceipt(arg1:string,arg2:string):Promise<void>;

export function ImportPGPKeyFromPath(arg1:string,arg2:string,arg3:string):Promise<pgp.ImportResult>;

export function ImportRecipientCert(arg1:string,arg2:string):Promise<void>;

export function ImportRecipientPGPKey(arg1:string,arg2:string):Promise<void>;

export function ImportSMIMECertificateFromPath(arg1:string,arg2:string,arg3:string):Promise<smime.ImportResult>;

export function InitiateShutdown():Promise<void>;

export function IsFTSIndexComplete(arg1:string):Promise<boolean>;

export function IsFTSIndexing():Promise<boolean>;

export function IsImageAllowed(arg1:string):Promise<boolean>;

export function IsOAuthConfigured(arg1:string):Promise<boolean>;

export function LinkAccountContactSource(arg1:string,arg2:string,arg3:number):Promise<carddav.Source>;

export function ListContacts(arg1:number):Promise<Array<contact.Contact>>;

export function ListDrafts(arg1:string):Promise<Array<draft.Draft>>;

export function ListPGPKeys(arg1:string):Promise<Array<pgp.Key>>;

export function ListPGPSenderKeys():Promise<Array<pgp.SenderKey>>;

export function ListSMIMECertificates(arg1:string):Promise<Array<smime.Certificate>>;

export function ListSenderCerts():Promise<Array<smime.SenderCert>>;

export function LookupHKP(arg1:string):Promise<string>;

export function LookupPGPKey(arg1:string):Promise<string>;

export function LookupWKD(arg1:string):Promise<string>;

export function MarkAllFolderMessagesAsRead(arg1:string):Promise<void>;

export function MarkAllFolderMessagesAsUnread(arg1:string):Promise<void>;

export function MarkAsNotSpam(arg1:Array<string>):Promise<void>;

export function MarkAsRead(arg1:Array<string>):Promise<void>;

export function MarkAsSpam(arg1:Array<string>):Promise<void>;

export function MarkAsUnread(arg1:Array<string>):Promise<void>;

export function MoveLocalMessages(arg1:Array<string>,arg2:string):Promise<void>;

export function MoveToFolder(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenAttachment(arg1:string):Promise<void>;

export function OpenComposerWindow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function OpenEncryptedAttachment(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickAttachmentFiles():Promise<Array<app.ComposerAttachment>>;

export function PickPGPKeyFile():Promise<string>;

export function PickRecipientCertFile():Promise<string>;

export function PickRecipientPGPKeyFile():Promise<string>;

export function PickSMIMECertificateFile():Promise<string>;

export function PrepareReply(arg1:string,arg2:string):Promise<smtp.ComposeMessage>;

export function ProcessPGPMessage(arg1:string):Promise<app.PGPViewResult>;

export function ProcessSMIMEMessage(arg1:string):Promise<app.SMIMEViewResult>;

export function QuitApp():Promise<void>;

export function ReadFileAsAttachment(arg1:string):Promise<app.ComposerAttachment>;

export function ReauthorizeAccount(arg1:string):Promise<void>;

export function RebuildFTSIndex(arg1:string):Promise<void>;

export function RefreshWindowConstraints():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RemoveImageAllowlist(arg1:number):Promise<void>;

export function RemovePGPKeyServer(arg1:number):Promise<void>;

export function RemoveTrustedCertificate(arg1:string):Promise<void>;

export function ReorderAccounts(arg1:Array<string>):Promise<void>;

export function SaveAllAttachments(arg1:string):Promise<string>;

export function SaveAllEncryptedAttachments(arg1:string):Promise<string>;

export function SaveAttachmentAs(arg1:string):Promise<string>;

export function SaveDraft(arg1:string,arg2:smtp.ComposeMessage,arg3:string):Promise<app.DraftResult>;

export function SaveEncryptedAttachmentAs(arg1:string,arg2:string):Promise<string>;

export function SaveOAuthTokens(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function SavePendingOAuthTokens(arg1:string):Promise<void>;

export function SaveUIState(arg1:appstate.UIState):Promise<void>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<contact.Contact>>;

export function SearchConversations(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<message.ConversationSearchResult>>;

export function SearchUnifiedInbox(arg1:string,arg2:number,arg3:number):Promise<Array<message.ConversationSearchResult>>;

export function SendMessage(arg1:string,arg2:smtp.ComposeMessage):Promise<void>;

export function SendReadReceipt(arg1:string,arg2:string):Promise<void>;

export function SetAccountEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAddressbookEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetDefaultIdentity(arg1:string,arg2:string):Promise<void>;

export function SetDefaultPGPKey(arg1:string,arg2:string):Promise<void>;

export function SetDefaultSMIMECertificate(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMarkAsReadDelay(arg1:number):Promise<void>;

export function SetMessageListDensity(arg1:string):Promise<void>;

export function SetMessageListSortOrder(arg1:string):Promise<void>;

export function SetPGPEncryptPolicy(arg1:string,arg2:string):Promise<void>;

export function SetPGPSignPolicy(arg1:string,arg2:string):Promise<void>;

export function SetReadReceiptResponsePolicy(arg1:string):Promise<void>;

export function SetRunBackground(arg1:boolean):Promise<void>;

export function SetSMIMEEncryptPolicy(arg1:string,arg2:string):Promise<void>;

export function SetSMIMESignPolicy(arg1:string,arg2:string):Promise<void>;

export function SetShowTitleBar(arg1:boolean):Promise<void>;

export function SetStartHidden(arg1:boolean):Promise<void>;

export function SetTermsAccepted(arg1:boolean):Promise<void>;

export function SetThemeMode(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function Star(arg1:Array<string>):Promise<void>;

export function StartContactsOnlyOAuthFlow(arg1:string):Promise<void>;

export function StartOAuthFlow(arg1:string):Promise<void>;

export function SyncAccountComplete(arg1:string):Promise<void>;

export function SyncAllComplete():Promise<void>;

export function SyncAllContactSources():Promise<void>;

export function SyncContactSource(arg1:string):Promise<void>;

export function SyncFolder(arg1:string,arg2:string):Promise<void>;

export function SyncFolders(arg1:string):Promise<void>;

export function SyncPendingDrafts(arg1:string):Promise<void>;

export function TestCardDAVConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestConnection(arg1:account.AccountConfig):Promise<app.ConnectionTestResult>;

export function TestOAuthConnection(arg1:string):Promise<void>;

export function TestSMTPConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function Trash(arg1:Array<string>):Promise<void>;

export function Undo():Promise<string>;

export function Unstar(arg1:Array<string>):Promise<void>;

export function UpdateAccount(arg1:string,arg2:account.AccountConfig):Promise<account.Account>;

export function UpdateContactSource(arg1:string,arg2:carddav.SourceConfig):Promise<void>;

export function UpdateIdentity(arg1:string,arg2:account.IdentityConfig):Promise<account.Identity>;

export function UpdateLocalFlags(arg1:Array<string>,arg2:any,arg3:any):Promise<void>;
