// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRecipientCerts(arg1) {
  return window['go']['app']['ComposerApp']['CheckRecipientCerts'](arg1);
}

export function CheckRecipientPGPKeys(arg1) {
  return window['go']['app']['ComposerApp']['CheckRecipientPGPKeys'](arg1);
}

export function CloseWindow() {
  return window['go']['app']['ComposerApp']['CloseWindow']();
}

export function DeleteDraft(arg1) {
  return window['go']['app']['ComposerApp']['DeleteDraft'](arg1);
}

export function GetAccount() {
  return window['go']['app']['ComposerApp']['GetAccount']();
}

export function GetComposeMode() {
  return window['go']['app']['ComposerApp']['GetComposeMode']();
}

export function GetDraft() {
  return window['go']['app']['ComposerApp']['GetDraft']();
}

export function GetIdentities() {
  return window['go']['app']['ComposerApp']['GetIdentities']();
}

export function GetOriginalMessage() {
  return window['go']['app']['ComposerApp']['GetOriginalMessage']();
}

export function GetPGPEncryptPolicy() {
  return window['go']['app']['ComposerApp']['GetPGPEncryptPolicy']();
}

export function GetPGPKeyForEmail(arg1) {
  return window['go']['app']['ComposerApp']['GetPGPKeyForEmail'](arg1);
}

export function GetPGPSignPolicy() {
  return window['go']['app']['ComposerApp']['GetPGPSignPolicy']();
}

export function GetSMIMECertificateForEmail(arg1) {
  return window['go']['app']['ComposerApp']['GetSMIMECertificateForEmail'](arg1);
}

export function GetSMIMEEncryptPolicy() {
  return window['go']['app']['ComposerApp']['GetSMIMEEncryptPolicy']();
}

export function GetSMIMESignPolicy() {
  return window['go']['app']['ComposerApp']['GetSMIMESignPolicy']();
}

export function GetSystemTheme() {
  return window['go']['app']['ComposerApp']['GetSystemTheme']();
}

export function GetThemeMode() {
  return window['go']['app']['ComposerApp']['GetThemeMode']();
}

export function HasPGPKey() {
  return window['go']['app']['ComposerApp']['HasPGPKey']();
}

export function HasSMIMECertificate() {
  return window['go']['app']['ComposerApp']['HasSMIMECertificate']();
}

export function ImportRecipientCert(arg1, arg2) {
  return window['go']['app']['ComposerApp']['ImportRecipientCert'](arg1, arg2);
}

export function ImportRecipientPGPKey(arg1, arg2) {
  return window['go']['app']['ComposerApp']['ImportRecipientPGPKey'](arg1, arg2);
}

export function LookupHKP(arg1) {
  return window['go']['app']['ComposerApp']['LookupHKP'](arg1);
}

export function LookupPGPKey(arg1) {
  return window['go']['app']['ComposerApp']['LookupPGPKey'](arg1);
}

export function LookupWKD(arg1) {
  return window['go']['app']['ComposerApp']['LookupWKD'](arg1);
}

export function PickAttachmentFiles() {
  return window['go']['app']['ComposerApp']['PickAttachmentFiles']();
}

export function PickRecipientCertFile() {
  return window['go']['app']['ComposerApp']['PickRecipientCertFile']();
}

export function PickRecipientPGPKeyFile() {
  return window['go']['app']['ComposerApp']['PickRecipientPGPKeyFile']();
}

export function PrepareReply() {
  return window['go']['app']['ComposerApp']['PrepareReply']();
}

export function RefreshWindowConstraints() {
  return window['go']['app']['ComposerApp']['RefreshWindowConstraints']();
}

export function SaveDraft(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SaveDraft'](arg1, arg2);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SearchContacts'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['app']['ComposerApp']['SendMessage'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['ComposerApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ComposerApp']['Startup'](arg1);
}
