// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {app} from '../models';
import {smtp} from '../models';
import {message} from '../models';
import {pgp} from '../models';
import {smime} from '../models';
import {draft} from '../models';
import {contact} from '../models';
import {context} from '../models';

export function CheckRecipientCerts(arg1:Array<string>):Promise<Record<string, boolean>>;

export function CheckRecipientPGPKeys(arg1:Array<string>):Promise<Record<string, boolean>>;

export function CloseWindow():Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function GetAccount():Promise<account.Account>;

export function GetComposeMode():Promise<app.ComposeMode>;

export function GetDraft():Promise<smtp.ComposeMessage>;

export function GetIdentities():Promise<Array<account.Identity>>;

export function GetOriginalMessage():Promise<message.Message>;

export function GetPGPEncryptPolicy():Promise<string>;

export function GetPGPKeyForEmail(arg1:string):Promise<pgp.Key>;

export function GetPGPSignPolicy():Promise<string>;

export function GetSMIMECertificateForEmail(arg1:string):Promise<smime.Certificate>;

export function GetSMIMEEncryptPolicy():Promise<string>;

export function GetSMIMESignPolicy():Promise<string>;

export function GetSystemTheme():Promise<string>;

export function GetThemeMode():Promise<string>;

export function HasPGPKey():Promise<boolean>;

export function HasSMIMECertificate():Promise<boolean>;

export function ImportRecipientCert(arg1:string,arg2:string):Promise<void>;

export function ImportRecipientPGPKey(arg1:string,arg2:string):Promise<void>;

export function LookupHKP(arg1:string):Promise<string>;

export function LookupPGPKey(arg1:string):Promise<string>;

export function LookupWKD(arg1:string):Promise<string>;

export function PickAttachmentFiles():Promise<Array<app.ComposerAttachment>>;

export function PickRecipientCertFile():Promise<string>;

export function PickRecipientPGPKeyFile():Promise<string>;

export function PrepareReply():Promise<smtp.ComposeMessage>;

export function RefreshWindowConstraints():Promise<void>;

export function SaveDraft(arg1:smtp.ComposeMessage,arg2:string):Promise<draft.Draft>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<contact.Contact>>;

export function SendMessage(arg1:smtp.ComposeMessage):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
