// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {app} from '../models';
import {smtp} from '../models';
import {message} from '../models';
import {draft} from '../models';
import {contact} from '../models';
import {context} from '../models';

export function CloseWindow():Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function GetAccount():Promise<account.Account>;

export function GetComposeMode():Promise<app.ComposeMode>;

export function GetDraft():Promise<smtp.ComposeMessage>;

export function GetIdentities():Promise<Array<account.Identity>>;

export function GetOriginalMessage():Promise<message.Message>;

export function GetThemeMode():Promise<string>;

export function PickAttachmentFiles():Promise<Array<app.ComposerAttachment>>;

export function PrepareReply():Promise<smtp.ComposeMessage>;

export function SaveDraft(arg1:smtp.ComposeMessage,arg2:string):Promise<draft.Draft>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<contact.Contact>>;

export function SendMessage(arg1:smtp.ComposeMessage):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
