// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['app']['ComposerApp']['CloseWindow']();
}

export function DeleteDraft(arg1) {
  return window['go']['app']['ComposerApp']['DeleteDraft'](arg1);
}

export function GetAccount() {
  return window['go']['app']['ComposerApp']['GetAccount']();
}

export function GetComposeMode() {
  return window['go']['app']['ComposerApp']['GetComposeMode']();
}

export function GetDraft() {
  return window['go']['app']['ComposerApp']['GetDraft']();
}

export function GetIdentities() {
  return window['go']['app']['ComposerApp']['GetIdentities']();
}

export function GetOriginalMessage() {
  return window['go']['app']['ComposerApp']['GetOriginalMessage']();
}

export function GetThemeMode() {
  return window['go']['app']['ComposerApp']['GetThemeMode']();
}

export function PickAttachmentFiles() {
  return window['go']['app']['ComposerApp']['PickAttachmentFiles']();
}

export function PrepareReply() {
  return window['go']['app']['ComposerApp']['PrepareReply']();
}

export function SaveDraft(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SaveDraft'](arg1, arg2);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SearchContacts'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['app']['ComposerApp']['SendMessage'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['ComposerApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ComposerApp']['Startup'](arg1);
}
